### ISSUE TITLE
Consider disable CSRF if a Valid OAuth token is provided

### ISSUE THREAD

**Issue by rwinch** [jzheaux/spring-security-oauth2-resource-server#17]
We should consider making it on by default or a feature to enable to disable CSRF protection if a valid OAuth token is provided. The reason for this is that an external site cannot submit a request from an external domain and expect that the OAuth token is automatically included.

**Comment by jzheaux** [comment]
What I'm thinking about here is registering a request matcher to the csrf filter that excludes requests which contain "Authorization: Bearer ". Is this too far removed from what you were thinking here: "disable CSRF protection if a valid OAuth token is provided"?

My thinking is this: if the request at least has the Bearer prefix in the Authorization header, then we fall back to the Bearer token authentication mechanism. If it is empty or invalid, we response with a 401 or 400 accordingly (instead of the 403 we'd get from the CSRF filter).

You can check out the commits attached to this ticket for some code that gets my idea across.
