### ISSUE TITLE
Do we need OAuth2TokenVerifier?

### ISSUE THREAD

**Issue by rwinch** [jzheaux/spring-security-oauth2-resource-server#25]
Other than in our AuthenticationProvider, where else do we need it? If we don't need it now, it is probably best to leave it out. We can always extract it later. If we do keep it around, why aren't we using a similar API for the existing client support?

**Comment by jgrandja** [comment]
We need to provide the capability for user's to configure their own custom claim/attribute verification. A common use case is verifying the `iss` claim. However, every application will have their own requirements and Authorization Server's may also put custom claims in JWT's that Resource Server's would verify against using the configured `OAuth2TokenVerifier`(s).

The reason it's in `org.springframework.security.oauth2.core` is because we may want to provide a feature on the client side to allow for ID Token verification beyond the standard ID Token Validation defined in the spec.

**Comment by jzheaux** [comment]
@jgrandja can correct me here, but I believe that the intent is to use it in the client code as well.

To address your question about need, though, I believe that it is certainly arguable independent of that.

There are two steps, as I see it, in validating a token. First, there is the processing step, which is essentially turning a token into a set of claims, or a String into a Map. Second, there is the verification of those claims, e.g. not expired and has my special custom claim.

If I am using Spring Security's Nimbus support, for example, and I have verification requirements that go beyond what it provides (expiresAt and notBefore), I would need to extend NimbusJwtDecoderJwkSupport or create my own JwtDecoder implementation.

This isn't the end of the world, of course, but having a different extension point seemed valuable since it will allow me to reuse it with non-JWT tokens.

**Comment by jgrandja** [comment]
@rwinch 

> a) OAuth2TokenVerifier should be put into oauth2-core

`OAuth2TokenVerifier` was explicitly placed in the package `org.springframework.security.oauth2.core` so when we're ready to put the PR together to bring in the Resource Server feature into Spring Security it will be placed in the `oauth2-core` module given that is the base package. Do you still feel the need an issue should be created?

> b) We should add support to the client support to use an OAuth2TokenVerifier

`OAuth2TokenVerifier` may be used in verifying additional claims in the `IdToken`. However, this feature hasn't been requested by any user as of yet. Do you think we should log a ticket for this and add the feature anyway?

**Comment by jgrandja** [comment]
@rwinch @jzheaux I'm starting to think the name `OAuth2TokenVerifier` may be misleading? The name may imply that it verifies the signature of the token, which is not it's purpose. As per javadoc:

> Implementations of this interface are responsible for "verifying" the validity and/or constraints of the attributes contained in an OAuth 2.0 Token.

Maybe we should change the name to `OAuth2TokenValidator`? Thoughts?

**Comment by rwinch** [comment]
@jgrandja I like the name change you suggested

**Comment by jzheaux** [comment]
Sounds like we are resolved on this one. There are tasks for adding samples of its usage as well as a new task, https://github.com/jzheaux/spring-security-oauth2-resource-server/issues/56, to take care of the rename that Joe suggested.
